version: '3.9'

services:
  postgres:
    image: postgres:13
    command: -c max_connections=5000
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always

  kong:
    image: "${GW_IMAGE:- }"
    command: sh -c "kong migrations bootstrap && kong start" --v
    ports:
      - '8000-8004:8000-8004'
    environment:
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_DATABASE: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ANONYMOUS_REPORTS: 'off'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002'
      KONG_ROUTER_FLAVOR: 'expressions'
    volumes:
      - "${GITHUB_WORKSPACE:-.}/kong_license.json:/etc/kong/license.json"
    restart: always
    depends_on:
      - postgres
