name: Sync Gateway schema

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 4 1 * *" # runs at 12:00 UTC+8 on the 1st day of every month

  workflow_dispatch:
    inputs:
      gateway-image:
        description: Image (leave empty to use branch-default nightly)
        type: string

jobs:
  sync-schema:
    name: Sync Gateway schema
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Select Gateway image
        id: select-gateway-image
        uses: ./.github/actions/select-gateway-image
        with:
          current-image: ${{ inputs.gateway-image }}

      - name: Log in to Docker Hub
        timeout-minutes: 1
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: kong
          password: ${{ secrets.OAT_KONG_DOCKER_PULL_PUBLIC }}

      - name: Start Gateway
        env:
          GATEWAY_IMAGE: ${{ steps.select-gateway-image.outputs.image }}
        run: |
          docker compose -f .ci/docker-compose.yml up -d

      - name: Execute node script
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm run exec

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.PAT }}
          commit-message: |-
            chore(schema): update schema
          branch: github-actions/update-main
          title: "chore(schema): update schema"
          labels: schema-update
          body: |-
            Updates Gateway schema. See details in [workflow run].

            [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          author: github-actions <github-actions@github.com>
          committer: github-actions <github-actions@github.com>
          signoff: true

      # - name: Send message to Slack channel
      #   if: ${{ steps.create-pr.outputs.pull-request-number }}
      #   uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
      #   with:
      #     channel-id: ${{ vars.SLACK_CI_CHANNEL_ID }}
      #     payload: |
      #       {
      #         "text": "🚨 A schema update PR is created: ${{ steps.create-pr.outputs.pull-request-url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "🚨 A schema update PR is created: ${{ steps.create-pr.outputs.pull-request-url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_KONG_MANAGER_CI_WATCHDOG_TOKEN }}
